### ISSUE TITLE
Quick Deploy link not available

### ISSUE THREAD

**Issue by billytotochan** [aws-quickstart/quickstart-progress-openedge#15]
Link not available. Deploy OpenEdge into a new VPC on AWS

![Screenshot 2021-04-01 at 10 56 30](https://user-images.githubusercontent.com/10459586/113237156-ef480d80-92d8-11eb-9fcd-001dae488e9a.png)

**Comment by davmayd** [comment]
@billytotochan thanks for catching this, it's been fixed. https://github.com/aws-quickstart/quickstart-progress-openedge/commit/56f1d052976698d3eb39ee9f3791da54e27d13a8
